"""zk_batch: ZK 证明批聚合验证服务。

公开入口：

* :func:`verify_batch` —— 按分组键聚合验证，失败回退单证验证。
* :func:`verify_batch_detailed` —— 同流水线的详细报告入口，
  返回 :class:`BatchVerificationReport`。
* :class:`VerificationQueue` —— 分组聚合的串行作业队列。
* :class:`VerificationTaskQueue` —— 可排队、可定位失败原因的逐项验证队列。
* :class:`ZKVerifier` —— 用户实现具体证明系统时继承的契约基类。
"""

from .errors import (
    BatchNotFoundError,
    BatchNotFoundException,
    BatchSizeLimitError,
    CancelledJobError,
    CompletedJobError,
    DuplicateItemIdError,
    DuplicateProofIdError,
    EmptyBatchError,
    GroupReverifyLineageMismatchError,
    IncompatibleAggregationError,
    InvalidAggregationGroupSelectionError,
    InvalidAggregationLimitError,
    InvalidGroupSelectionError,
    InvalidItemIdError,
    InvalidPriorityError,
    InvalidProofError,
    InvalidProofFormatError,
    InvalidRetrySelectionError,
    InvalidRetrySelectionException,
    NoFailedProofError,
    NoRetryableItemsError,
    ProofNotInBatchError,
    ProofNotInBatchException,
    ResultUnavailableError,
    ReverifyLineageMismatchError,
    RunningJobError,
    TaskLineageMismatchError,
    TaskNotFoundError,
    TaskStateConflictError,
    UnknownAggregationGroupError,
    UnknownFailedGroupError,
    UnknownJobError,
    UnsupportedProofSystemError,
    VerificationInfrastructureError,
    VerifierContractError,
)
from .models import (
    RETRY_SKIP_ALREADY_COMPLETED,
    RETRY_SKIP_ALREADY_QUEUED,
    RETRY_SKIP_NOT_RETRYABLE,
    RETRY_SKIP_PROOF_NOT_IN_BATCH,
    RETRY_SKIP_REASONS,
    RETRY_SKIP_UNKNOWN_PROOF,
    AggregationConflictReport,
    BatchSummary,
    BatchVerificationReport,
    BatchVerificationResult,
    BatchTaskResult,
    Failure,
    GroupReverifyGroupItem,
    GroupReverifyOutcomeReport,
    GroupReverifyProofItem,
    GroupReverifySubmission,
    GroupVerificationReport,
    ItemResult,
    MAX_BATCH_ITEMS,
    MAX_TASK_PRIORITY,
    MIN_TASK_PRIORITY,
    Proof,
    ProofRetrySkip,
    ProofRetrySubmission,
    ProofVerificationDetail,
    RetryOutcomeItem,
    RetryOutcomeReport,
    ReverifyOutcomeItem,
    ReverifyOutcomeReport,
    TaskCancellationReceipt,
    TaskProgress,
    TaskRetrySubmission,
    TaskScheduleEntry,
    TaskScheduleReport,
    TaskSubmission,
    VerificationJob,
    WindowedBatchVerificationReport,
    WindowVerificationReport,
)
from .queue import VerificationQueue
from .tasks import VerificationTaskQueue
from .verifier import ZKVerifier
from .engine import (
    diagnose_aggregation_conflict,
    verify_batch,
    verify_batch_detailed,
    verify_batch_windowed,
)

__all__ = [
    "verify_batch",
    "verify_batch_detailed",
    "verify_batch_windowed",
    "diagnose_aggregation_conflict",
    "VerificationQueue",
    "VerificationTaskQueue",
    "ZKVerifier",
    "Proof",
    "Failure",
    "BatchVerificationResult",
    "BatchVerificationReport",
    "GroupVerificationReport",
    "ProofVerificationDetail",
    "WindowVerificationReport",
    "WindowedBatchVerificationReport",
    "AggregationConflictReport",
    "VerificationJob",
    "ItemResult",
    "BatchTaskResult",
    "BatchSummary",
    "TaskSubmission",
    "TaskRetrySubmission",
    "TaskCancellationReceipt",
    "TaskProgress",
    "TaskScheduleEntry",
    "TaskScheduleReport",
    "RetryOutcomeItem",
    "RetryOutcomeReport",
    "ReverifyOutcomeItem",
    "ReverifyOutcomeReport",
    "GroupReverifySubmission",
    "GroupReverifyGroupItem",
    "GroupReverifyProofItem",
    "GroupReverifyOutcomeReport",
    "ProofRetrySubmission",
    "ProofRetrySkip",
    "RETRY_SKIP_UNKNOWN_PROOF",
    "RETRY_SKIP_PROOF_NOT_IN_BATCH",
    "RETRY_SKIP_NOT_RETRYABLE",
    "RETRY_SKIP_ALREADY_QUEUED",
    "RETRY_SKIP_ALREADY_COMPLETED",
    "RETRY_SKIP_REASONS",
    "MAX_BATCH_ITEMS",
    "MIN_TASK_PRIORITY",
    "MAX_TASK_PRIORITY",
    "EmptyBatchError",
    "InvalidProofError",
    "DuplicateProofIdError",
    "IncompatibleAggregationError",
    "UnsupportedProofSystemError",
    "VerifierContractError",
    "InvalidAggregationLimitError",
    "InvalidAggregationGroupSelectionError",
    "UnknownAggregationGroupError",
    "RunningJobError",
    "CompletedJobError",
    "CancelledJobError",
    "UnknownJobError",
    "ResultUnavailableError",
    "NoFailedProofError",
    "ReverifyLineageMismatchError",
    "InvalidGroupSelectionError",
    "UnknownFailedGroupError",
    "GroupReverifyLineageMismatchError",
    "BatchNotFoundException",
    "ProofNotInBatchException",
    "InvalidRetrySelectionException",
    "BatchNotFoundError",
    "ProofNotInBatchError",
    "InvalidRetrySelectionError",
    "NoRetryableItemsError",
    "DuplicateItemIdError",
    "InvalidItemIdError",
    "BatchSizeLimitError",
    "InvalidProofFormatError",
    "InvalidPriorityError",
    "TaskNotFoundError",
    "TaskStateConflictError",
    "TaskLineageMismatchError",
    "VerificationInfrastructureError",
]
